
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: resourcequotaclaims.claim.tmax.io
spec:
  additionalPrinterColumns:
  - JSONPath: .resourceName
    name: ResourceName
    type: string
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.reason
    name: Reason
    type: string
  group: claim.tmax.io
  names:
    kind: ResourceQuotaClaim
    listKind: ResourceQuotaClaimList
    plural: resourcequotaclaims
    shortNames:
    - rqc
    singular: resourcequotaclaim
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ResourceQuotaClaim is the Schema for the resourcequotaclaims API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        resourceName:
          type: string
        spec:
          description: ResourceQuotaSpec defines the desired hard limits to enforce
            for Quota.
          properties:
            hard:
              additionalProperties:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              description: 'hard is the set of desired hard limits for each named
                resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/'
              type: object
            scopeSelector:
              description: scopeSelector is also a collection of filters like scopes
                that must match each object tracked by a quota but expressed using
                ScopeSelectorOperator in combination with possible values. For a resource
                to match, both scopes AND scopeSelector (if specified in spec), must
                be matched.
              properties:
                matchExpressions:
                  description: A list of scope selector requirements by scope of the
                    resources.
                  items:
                    description: A scoped-resource selector requirement is a selector
                      that contains values, a scope name, and an operator that relates
                      the scope name and values.
                    properties:
                      operator:
                        description: Represents a scope's relationship to a set of
                          values. Valid operators are In, NotIn, Exists, DoesNotExist.
                        type: string
                      scopeName:
                        description: The name of the scope that the selector applies
                          to.
                        type: string
                      values:
                        description: An array of string values. If the operator is
                          In or NotIn, the values array must be non-empty. If the
                          operator is Exists or DoesNotExist, the values array must
                          be empty. This array is replaced during a strategic merge
                          patch.
                        items:
                          type: string
                        type: array
                    required:
                    - operator
                    - scopeName
                    type: object
                  type: array
              type: object
            scopes:
              description: A collection of filters that must match each object tracked
                by a quota. If not specified, the quota matches all objects.
              items:
                description: A ResourceQuotaScope defines a filter that must match
                  each object tracked by a quota
                type: string
              type: array
          type: object
        status:
          description: ResourceQuotaClaimStatus defines the observed state of ResourceQuotaClaim
          properties:
            lastTransitionTime:
              format: date-time
              type: string
            message:
              type: string
            reason:
              type: string
            status:
              enum:
              - Awaiting
              - Success
              - Reject
              - Error
              type: string
          type: object
      required:
      - resourceName
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
